defaults:
  - default
  - tabularization: default
  - _self_

# Raw data
# Where the code metadata is stored
input_code_metadata: ${MEDS_cohort_dir}/code_metadata.parquet
input_dir: ${MEDS_cohort_dir}/final_cohort
output_dir: ${MEDS_cohort_dir}/tabularize
