defaults:
  - default
  - tabularization: default
  - _self_

# Raw data
# Where the code metadata is stored
input_code_metadata_fp: ${output_cohort_dir}/metadata/codes.parquet
input_dir: ${MEDS_cohort_dir}/data
output_dir: ${output_cohort_dir}/tabularize

name: tabularization
