defaults:
  - default
  - tabularization: default
  - _self_
task_name: ???

# Directory of tabularized data
input_tabularized_dir: ${output_dir}/tabularize
# Where the labels are stored, with columns subject_id, timestamp, label
input_label_dir: ???
# Where to output the task, split, and shard specific tabularized data
output_tabularized_cache_dir: ${output_dir}/${task_name}/task_cache
# Where to output the task, split, and shard specific label data
output_label_cache_dir: ${output_dir}/${task_name}/labels

label_column: "boolean_value"

name: task_specific_caching
